"""Add new column to Room

Revision ID: 77cd7d4e56ee
Revises: 372f300bfb54
Create Date: 2025-05-19 15:20:38.177892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77cd7d4e56ee'
down_revision: Union[str, None] = '372f300bfb54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('status', sa.Boolean(), server_default='False', nullable=True))
    op.add_column('users', sa.Column('status', sa.Boolean(), server_default='False', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'status')
    op.drop_column('admins', 'status')
    # ### end Alembic commands ###
